### ISSUE TITLE
boiledIp seems to append forever

### ISSUE THREAD

**Issue by spacerockzero** [johnnymastin/check-ip#1]
every time I ran the function, the boiledIp appends the input ip on the end, forever...

**Comment by johnnymastin** [comment]
Hi there, Jakob!  Can you give me a sample IP address that you're using which triggers this condition?  I saw something similar when first writing this script but I could have sworn I fixed it.

**Comment by johnnymastin** [comment]
I was able to duplicate the issue seen.  Fix was to move the boiledArray and answer object into the function so that they would be reset to default values each time the function was called.  Fix will be part of version 1.0.1.

**Comment by spacerockzero** [comment]
thank you!

**Comment by johnnymastin** [comment]
Thank you for bringing it to my attention, sir!
